package structs

type BootstrapData struct {
	CollegeTeam                CollegeTeam
	AllCollegeTeams            []CollegeTeam
	CollegeStandings           []CollegeStandings
	CollegeRosterMap           map[uint][]CollegePlayer
	Recruits                   []Croot
	RecruitProfiles            []RecruitPlayerProfile
	TeamProfileMap             map[uint]*RecruitingTeamProfile
	PortalPlayers              []CollegePlayer
	TransferPortalProfiles     []TransferPortalProfile
	CollegePromises            []CollegePromise
	CollegeInjuryReport        []CollegePlayer
	CollegeNews                []NewsLog
	CollegeNotifications       []Notification
	AllCollegeGames            []CollegeGame
	CHLGameplanMap             map[uint]CollegeGameplan
	CollegeLineupsMap          map[uint][]CollegeLineup
	CollegeTeamLineups         []CollegeLineup
	CollegeTeamShootoutLineup  CollegeShootoutLineup
	CollegeShootoutLineupsMap  map[uint]CollegeShootoutLineup
	TopCHLGoals                []CollegePlayer
	TopCHLAssists              []CollegePlayer
	TopCHLSaves                []CollegePlayer
	CollegePoll                CollegePollSubmission
	OfficialPolls              []CollegePollOfficial
	HockeyInvitationals        []HockeyInvitational
	HockeyInvitationalRequests []HockeyInvitationalRequest
	CollegeGameRequests        []CHLGameRequest
	// Player Profiles by Team?
	// Portal profiles?
	ProTeam               ProfessionalTeam
	AllProTeams           []ProfessionalTeam
	ProStandings          []ProfessionalStandings
	ProRosterMap          map[uint][]ProfessionalPlayer
	AffiliatePlayers      []ProfessionalPlayer
	TopPHLGoals           []ProfessionalPlayer
	TopPHLAssists         []ProfessionalPlayer
	TopPHLSaves           []ProfessionalPlayer
	FreeAgentOffers       []FreeAgencyOffer
	WaiverWireOffers      []WaiverOffer
	CapsheetMap           map[uint]ProCapsheet
	ProInjuryReport       []ProfessionalPlayer
	ProNews               []NewsLog
	ProNotifications      []Notification
	AllProGames           []ProfessionalGame
	PHLGameplanMap        map[uint]ProGameplan
	ProLineupsMap         map[uint][]ProfessionalLineup
	ProTeamLineups        []ProfessionalLineup
	ProShootoutLineupsMap map[uint]ProfessionalShootoutLineup
	ProTeamShootoutLineup ProfessionalShootoutLineup
	FaceData              map[uint]FaceDataResponse
	ContractMap           map[uint]ProContract
	ExtensionMap          map[uint]ExtensionOffer
	ProTradeProposalMap   map[uint][]TradeProposal
	ProTradePreferenceMap map[uint]TradePreferences
	DraftPicks            map[uint][]DraftPick
	DraftablePlayers      []DraftablePlayer
}
